### ISSUE TITLE
Cannot parse arguments with "/"

### ISSUE THREAD

**Issue by Calo-go** [SuperH-0630/fflags#2]
When I want to parse the argumnet with -c "/dev/ttyS1", I get an error.

The log is:
```
Program do not get a argument after option. [-c]
```

**Comment by SongZihuan** [comment]
我在项目中添加了新的测试代码，测试2（test2）可以识别参数 -c "dev/ttyS1"，你可以参考一下。
I added a new test code to the project, test 2 can recognize the parameter -c "dev/ttyS1", you can refer to it.

**Comment by SongZihuan** [comment]
或者你可以让我看看你代码中参数匹配的部分。
Or you can show me the part of your code where the parameter matches.

**Comment by Calo-go** [comment]
> 

参数需要是 -c "/dev/ttyS1"，你少了个前置/

**Comment by Calo-go** [comment]
参数匹配部分很简单
```
ff_defArg(main, true)
    ff_argRule('c', "com", must, 1)
ff_endArg(main, true);
```

这里面应该是因为你想兼容Windows下面‘/’引起的。在Linux里面以'/'开头的参数会比较频繁，所以如果想兼容的话，建议是通过下面的方式进行：
```
#ifdef _WIN32
xxxxx在Windows上运行的代码
#else
xxxxx在Linux上运行的代码
#endif
在Windows下_WIN32函数被定义为1，在Linux下无定义，为0
```

**Comment by SongZihuan** [comment]
问题修复了，你试一下

**Comment by Calo-go** [comment]
> 问题修复了，你试一下

OK，谢谢，可以了
